chanzuckerberg/happy

- cmd/create.go
- pkg/config/happy_config.go
- pkg/config/happy_config_test.go
- pkg/config/testdata/test_config.yaml
the python version uses `auto_run_migrations`, let's match it
> fix!: match existing config key to auto_run_migrations

- .github/workflows/release.yaml
going by https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability, the contexts and their availability. in particular, s/jobs/needs/ context.
> fix: GitHub Release action s/jobs/needs/

- cmd/build.go
- pkg/artifact_builder/builder_config.go
- pkg/artifact_builder/docker_compose.go
We're using `docker compose` in the CLI rather than `docker-compose` so this updates error/help text and comments accordingly
> fix: Don't refer to docker-compose anymore

- pkg/artifact_builder/docker_compose.go
I'm not sure why buildkit is disabled in this CLI. It's enabled in the python script, and omission of buildkit is causing `docker compose` to ignore my `platform` flags.
> fix: Docker uses buildkit

- .github/workflows/cli-release.yaml
After changing tagging structure for the monorepo from `vX.X.X` to `cli-vX.X.X` goreleaser broke: https://github.com/chanzuckerberg/happy/actions/runs/3206117658/jobs/5239465071
This passes a version to goreleaser that does not have the `cli-` prefix
> fix: specify version correctly

- .github/workflows/cli-release.yaml
- cli/file.txt
The tag needs to exist before goreleaser can use a custom version
> fix: create tag for goreleaser

- .github/workflows/cli-release.yaml
- cli/file.txt
This failed but a re-run will pass because the tag does exist: https://github.com/chanzuckerberg/happy/actions/runs/3228253227/jobs/5284105709
Increase the sleep time in hopes that the tag will sync and we can avoid the re-runs
> fix: increase sleep time after tag creation

- release-please-config.json
No longer need release to be pinned now that the initial terraform provider version has been released
> chore: unpin release

- .github/workflows/api-release-staging.yaml
- api/.happy/terraform/envs/prod/main.tf
- api/.happy/terraform/envs/rdev/main.tf
- api/.happy/terraform/envs/staging/main.tf
staging is now accessible at https://happy-api.api.staging.si.czi.technology/health (instead of https://happy-api-happy-api.api.staging.si.czi.technology/health)
> fix: simplify staging/prod dns routing

- terraform/modules/happy-env-ecs/README.md
- terraform/modules/happy-env-ecs/proxy.tf
- terraform/modules/happy-env-eks/README.md
- terraform/modules/happy-env-eks/proxy.tf
Update the happy modules to the latest versions of the proxy which expose metrics on the nginx and oauth2_proxy containers.
> chore: bump version of proxy -- metrics

- terraform/modules/happy-env-ecs/README.md
- terraform/modules/happy-env-ecs/proxy.tf
Reverting to using our old image so that we can use Chamber to pull secrets. New fargate networking prevents us from calling SSM.
> fix: happy env ecs

- terraform/modules/happy-stack-eks/README.md
- terraform/modules/happy-stack-eks/synthetics.tf
- terraform/modules/happy-stack-eks/variables.tf
- terraform/modules/happy-stack-eks/versions.tf
Example: https://app.datadoghq.com/synthetics/details/thu-n4e-6e5
Looks like this:
If you choose to opt in (probably most effective for production deployments), you can turn on synthetic testing of your services in EKS.
> feat: add synthetics to happy stack services

- cli/cmd/push.go
- cli/pkg/cmd/validate.go
This PR updates the push command so that it pushes to the ECRs that are specific to the stack name provided. Before, no stack argument was required.
> fix: push command to push to stack ECRs

- terraform/modules/happy-env-eks/dynamo.tf
We don't need these attributes since the dynamo table is PAY_PER_REQUEST
> fix: remove optional arguments for ppr

- cli/cmd/root.go
- cli/cmd/version.go
- cli/pkg/config/happy_version_lock.go
Implement (currently optional) Happy version locking in repos.
Scenarios:
- Fail check silently and proceed if we can't get the latest available version (generally if we are outside a project root)
- Allow for version, available-version, and set-lock commands to exclude locked version check
- Allow for legacy behavior if no lockfile is present (i.e. proceed with any version)
- Refuse to run for most commands if lockfile is present and version does not match
> feat: CCIE-858: lock the version of happy cli in a repo like fogg

- terraform/modules/happy-iam-service-account-eks/README.md
- terraform/modules/happy-iam-service-account-eks/main.tf
We want to be able to attach multiple policies to the service role. Per the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment), using an iam_policy_attachment resource creates an exclusive attachment of iam policies.
> The aws_iam_policy_attachment resource creates exclusive attachments of IAM policies. Across the entire AWS account, all of the users/roles/groups to which a single policy is attached must be declared by a single aws_iam_policy_attachment resource. This means that even any users/roles/groups that have the attached policy via any other mechanism (including other Terraform resources) will have that attached policy revoked by this resource. Consider aws_iam_role_policy_attachment, aws_iam_user_policy_attachment, …
> feat: use aws_iam_role_policy_attachment resource to allow multiple polices per role

- terraform/modules/happy-env-eks/README.md
- terraform/modules/happy-env-eks/outputs.tf
This will allow us to pull in this output for setting up debezium connectors (which need to connect to these RDSs) without manually copying them into SSM
> feat: CDI-1356 - add database creds to output

- terraform/modules/happy-env-eks/integration_secret.tf
The waf module is an array so need to index it.
> fix: waf is a count

- terraform/modules/happy-service-eks/iam.tf
A service role isn't created unless the policy json is not empty. We'd like to be able to attach policies on the role outside of the `aws_iam_policy_json` field. It'd be helpful if this role was always created
> chore: Always create iam service role

- api/pkg/cmd/stack.go
- shared/workspace_repo/workspace.go
- shared/workspace_repo/workspace_test.go
This PR fixes an issue in the API where if the TFE workspace doesn't have any state (as in, there have been no applies or if there was an error on their first apply), the state information is not populated. This leads to a nil pointer exception. This PR handles this by always checking for state and returning empty information if no state.
> fix: workspaces with no state will not have info

- api/go.mod
- api/go.sum
- cli/go.mod
- cli/go.sum
- shared/util/tf/tf_generator.go
This fix will address a problem related to inconsistently configured services when attempting to run `happy infra generate` by supplementing missing values with module defaults.
> fix: When more than one service is specified, and the settings structure is inconsistent, happy infra generate errors out

- terraform/modules/happy-stack-eks/main.tf
This PR addresses the following issue:
```
╷
│ Error: Invalid template interpolation value
│ 
│   on .terraform/modules/stack/terraform/modules/happy-stack-eks/main.tf line 84, in locals:
│   84:       "PRIVATE_${upper(replace(k, "-", "_"))}_ENDPOINT" = "${lower(v.service_scheme)}://${v.service_name}.${var.k8s_namespace}.svc.cluster.local:${v.service_port}"
│     ├────────────────
│     │ v.service_port is null
│ 
│ The expression result is null. Cannot include a null value in a string
│ template.
```
> fix: Service port is not populated

- terraform/modules/happy-env-ecs/README.md
- terraform/modules/happy-env-ecs/s3.tf
- terraform/modules/happy-env-eks/README.md
- terraform/modules/happy-env-eks/ecr.tf
- terraform/modules/happy-env-eks/s3.tf
- terraform/modules/happy-service-eks/README.md
- terraform/modules/happy-service-eks/ecr.tf
See https://github.com/chanzuckerberg/cztack/pull/494 for additional details. This PR is to fix the following error:
```
│ Error: Unsupported argument
│ 
│   on .terraform/modules/stack.services.ecr/aws-ecr-repo/main.tf line 99, in data "aws_iam_policy_document" "policy":
│   99:   source_json = var.ecr_resource_policy
│ 
│ An argument named "source_json" is not expected here.
```
Customer impact: https://chanzuckerbergteam.slack.com/archives/C01C310V70X/p1685041757045689 and https://chanzuckerbergteam.slack.com/archives/C04NVSCDFR7/p1685133258183989
> fix: aws provider 5.0 deprecated source_json

- api/pkg/cmd/stack.go
The workspace information is gathered by goroutines, so the credential check is preferred by a single worker. However, the worker pool wasn't started in the API causing the channel to block and return 504 timeout errors on calls to the stacklist API.
> fix: deadlock in API by not starting worker pool

- terraform/modules/happy-tfe-okta-service-account/ssm_writer.tf
Happy API now is hosted on EKS, so we need to update the path these parameters land so they are picked up by SSM controller. Tested with eng-portal migration and it seems to work well.
> feat: change SSM location to k8s secret

- .github/workflows/integration-test.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1601" title="CCIE-1601" target="_blank">CCIE-1601</a></summary>
<br />
<table>
<tr>
<td>Integration test fails because dependencies need tidy</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Fixes [CCIE-1601]
[CCIE-1601]: https://czi-tech.atlassian.net/browse/CCIE-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Tidy cli dependencies in integration test

- cli/cmd/list.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1603" title="CCIE-1603" target="_blank">CCIE-1603</a></summary>
<br />
<table>
<tr>
<td>'happy list --output json'  returns an invalid value</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Fixes [CCIE-1603]; previously returned `null`, where an array is expected, when no matching stacks are found.
[CCIE-1603]: https://czi-tech.atlassian.net/browse/CCIE-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 'happy list --output json' returns an invalid value

- .github/workflows/integration-test.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1603" title="CCIE-1603" target="_blank">CCIE-1603</a></summary>
<br />
<table>
<tr>
<td>'happy list --output json'  returns an invalid value</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
Fixes [CCIE-1603]
[CCIE-1603]: https://czi-tech.atlassian.net/browse/CCIE-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix stack info retrieval from json output in integration test (.name got replaced by .stack)

- terraform/modules/happy-env-eks/db.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1506" title="CCIE-1506" target="_blank">CCIE-1506</a></summary>
<br />
<table>
<tr>
<td>Move eng-portal to EKS</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1506
> fix: underscores in db parameter groups

- .github/workflows/integration-test.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1667" title="CCIE-1667" target="_blank">CCIE-1667</a></summary>
<br />
<table>
<tr>
<td>Running integration test on a PR blocks concurrent PRs (dependabot)</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
Addresses [CCIE-1667].
[CCIE-1667]: https://czi-tech.atlassian.net/browse/CCIE-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Make integration test run on push to main, and not on pr

- .github/workflows/integration-test.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1687" title="CCIE-1687" target="_blank">CCIE-1687</a></summary>
<br />
<table>
<tr>
<td>Happy Integration test is being cancelled in-flight</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1687]
[CCIE-1687]: https://czi-tech.atlassian.net/browse/CCIE-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Prevent abrupt integration test cancellations

- terraform/modules/happy-env-eks/s3.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1702" title="CCIE-1702" target="_blank">CCIE-1702</a></summary>
<br />
<table>
<tr>
<td>Allow for Bucket Policies to be Configured for Happy S3 Buckets</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1702
This PR allows for bucket policies to be configured, which is required if roles outside the scope of the happy environment need to write to the bucket.
> fix: allow for a bucket policy to be specified

- terraform/modules/happy-service-eks/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-865" title="CCIE-865" target="_blank">CCIE-865</a></summary>
<br />
<table>
<tr>
<td>Happy update reports success on failed deployment when ECS rolls back the task version</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
[CCIE-865]
[CCIE-865]: https://czi-tech.atlassian.net/browse/CCIE-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Only Always restart policy is supported

- .github/workflows/cli-ci.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1714" title="CCIE-1714" target="_blank">CCIE-1714</a></summary>
<br />
<table>
<tr>
<td>Skip coverage updates on dependabot PRs</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1714]
[CCIE-1714]: https://czi-tech.atlassian.net/browse/CCIE-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Skip coverage update on dependabot commits

- terraform/modules/happy-iam-service-account-eks/README.md
- terraform/modules/happy-iam-service-account-eks/main.tf
- terraform/modules/happy-iam-service-account-eks/variables.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1749" title="CCIE-1749" target="_blank">CCIE-1749</a></summary>
<br />
<table>
<tr>
<td>Allow for Adding Multiple Policies to a Single Service Account Role</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1749
This PR allows us to attach multiple policies to the same service account. I needed this because I ran out of bytes in a single policy.
> feat: allow for multiple polices on IAM service account

- terraform/modules/happy-iam-service-account-eks/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1749" title="CCIE-1749" target="_blank">CCIE-1749</a></summary>
<br />
<table>
<tr>
<td>Allow for Adding Multiple Policies to a Single Service Account Role</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1749](https://czi-tech.atlassian.net/browse/CCIE-1749)
oops
[CCIE-1749]: https://czi-tech.atlassian.net/browse/CCIE-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: forgot length argument for count

- terraform/modules/happy-iam-service-account-eks/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1749" title="CCIE-1749" target="_blank">CCIE-1749</a></summary>
<br />
<table>
<tr>
<td>Allow for Adding Multiple Policies to a Single Service Account Role</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1749](https://czi-tech.atlassian.net/browse/CCIE-1749)
[CCIE-1749]: https://czi-tech.atlassian.net/browse/CCIE-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: make policy names unique

- terraform/modules/happy-iam-service-account-eks/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1749" title="CCIE-1749" target="_blank">CCIE-1749</a></summary>
<br />
<table>
<tr>
<td>Allow for Adding Multiple Policies to a Single Service Account Role</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1749](https://czi-tech.atlassian.net/browse/CCIE-1749)
Fixes a bug where the default empty strings we being used to make the policy. Compat removes the empty string enties.
[CCIE-1749]: https://czi-tech.atlassian.net/browse/CCIE-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: don't use empty strings when making policies

- shared/util/tf/tf_generator.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1237" title="CCIE-1237" target="_blank">CCIE-1237</a></summary>
<br />
<table>
<tr>
<td>DRY -  happy stack app_name</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Tested locally using the debugger tools that runs `happy infra generate --force`. When this run is triggered, it would fail on this error, 
`[FATAL]: unable to generate HCL code: Unable to generate main.tf: unable to generate nested values: field 'name' is required, there's no value provided, and no default field value set in the module`. I commented out this [line](https://github.com/chanzuckerberg/happy/blob/main/shared/util/tf/tf_generator.go#L319) that was …
> feat: Added app name field to be included in auto-generated field

- shared/workspace_repo/workspace.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1754" title="CCIE-1754" target="_blank">CCIE-1754</a></summary>
<br />
<table>
<tr>
<td>Happy TFE/TFC messages are inconsistent</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1754]. Addresses message consistency issues.
[CCIE-1754]: https://czi-tech.atlassian.net/browse/CCIE-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Make workspace run message consistent

- cli/cmd/init.go
- examples/nodejs_downstream/backend/Dockerfile
- shared/util/preconditions.go
Version constraint altered to fix the following error: 
```
[FATAL]: 2 errors occurred:
* docker compose >= V2 required but 2.20.2-desktop.1 was detected, please follow https://docs.docker.com/compose/cli-command/
* 2.20.2-desktop.1 is a prerelease version and the constraint is only looking for release versions
```
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1757" title="CCIE-1757" target="_blank">CCIE-1757</a></summary>
<br />
<table>
<tr>
<td>Happy create freezes</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1757]
[CCIE-1757]: https://czi-tech.atlassian.net/browse/CCIE-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> fix: Notify user to restart docker engine, allow pre-release for docker compose

- cli/cmd/create.go
- cli/cmd/init.go
- cli/cmd/update.go
- shared/config/bootstrap.go
- shared/config/bootstrap_test.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1776" title="CCIE-1776" target="_blank">CCIE-1776</a></summary>
<br />
<table>
<tr>
<td>Happy CLI Promote Images Does Not Obey --aws-profile Flag</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1776
This fixes a bug in the happy CLI that was trying to use the happy config.json every time image promotion happened. In Github Actions, we still want to obey the `--aws-profile ""` flag. This PR fixes this issue to look at this flag when making its happy clients for the various environments it is trying to promote from.
> fix: using the wrong AWS profile when promoting images

- terraform/modules/happy-env-ecs/README.md
- terraform/modules/happy-env-ecs/proxy.tf
- terraform/modules/happy-env-ecs/variables.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1825" title="CCIE-1825" target="_blank">CCIE-1825</a></summary>
<br />
<table>
<tr>
<td>Upgrade OAuth2 Proxy for Single Cell</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1825
This bump allows users to change the container version of oauth2_proxy.
> feat: bump the ecs multidomain proxy module

- api/pkg/request/auth.go
- cli/cmd/version.go
- shared/client/util.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1124" title="CCIE-1124" target="_blank">CCIE-1124</a></summary>
<br />
<table>
<tr>
<td>Better Error/Log Writing For the Happy API</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
- Improved error reporting for `MultiOIDCProvider` (by using multierrors)
- Improved error parsing for Hapi responses in the CLI and TF provider
Examples of fixed parsing:
This one shows fixed parsing as well as the use of multierror:
> fix: better error reporting for happy cli and happy tf provider

- terraform/modules/happy-env-eks/ecr.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1902" title="CCIE-1902" target="_blank">CCIE-1902</a></summary>
<br />
<table>
<tr>
<td>When ECR scanning is not enable, happy update fails</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1902]
[CCIE-1902]: https://czi-tech.atlassian.net/browse/CCIE-1902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix scan on push typo

- terraform/modules/happy-env-eks/README.md
- terraform/modules/happy-github-ci-role/ecr.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1906" title="CCIE-1906" target="_blank">CCIE-1906</a></summary>
<br />
<table>
<tr>
<td>ECR scan times out</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1906]
[CCIE-1906]: https://czi-tech.atlassian.net/browse/CCIE-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Add permissions to github ci role to allow retrieval of ecr image scanning

- terraform/provider/pkg/provider/provider.go
- terraform/provider/pkg/provider/provider_test.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1780" title="CCIE-1780" target="_blank">CCIE-1780</a></summary>
<br />
<table>
<tr>
<td>Create custom claim for happy api tokens from happy tf provider</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Adds a custom Actor claim to jwts generated by the happy provider. This allows us to better label transactions sent to Sentry from the happy api.
> feat: add custom claim to jwts sent from happy provider to happy api

- terraform/provider/pkg/provider/provider.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1780" title="CCIE-1780" target="_blank">CCIE-1780</a></summary>
<br />
<table>
<tr>
<td>Create custom claim for happy api tokens from happy tf provider</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Follow-up to https://github.com/chanzuckerberg/happy/pull/2505
> fix: pass role to assume arn to token providers

- shared/util/tf/tf_generator.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1926" title="CCIE-1926" target="_blank">CCIE-1926</a></summary>
<br />
<table>
<tr>
<td>Create Default Tag in AWS Provider in fogg.tf</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
Similar to `fogg.tf`, we want to tag the AWS resources with the following format
```
provider "aws" {
region = "us-west-2"
assume_role {
role_arn = "arn:aws:iam::626314663667:role/tfe-si"
}
default_tags {
tags = {
TFC_RUN_ID                               = var.TFC_RUN_ID
TFC_WORKSPACE_NAME                       = var.TFC_WORKSPACE_NAME
TFC_WORKSPACE_SLUG                       = var.TFC_WORKSPACE_SLUG
TFC_CONFIGURATION_VERSION_GIT_BRANCH     = …
```
> feat: autogenerate default_tag field in aws provider when using happy infra generate command

- terraform/modules/happy-service-eks/target_group_only.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1985" title="CCIE-1985" target="_blank">CCIE-1985</a></summary>
<br />
<table>
<tr>
<td>Happy: TARGET_GROUP_ONLY stacks cannot be deleted and recreated</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1985?atlOrigin=eyJpIjoiZDI3Y2ExZWZjYzI0NDQxZTk0ODA4ZjUzNDRiNGMzNzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ
We need to use the random pet ID to get an actual random ID attached to the target group name. Otherwise, stacks of the same name will conflict.
> fix: duplicate target group names

- terraform/modules/happy-service-eks/target_group_only.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1985" title="CCIE-1985" target="_blank">CCIE-1985</a></summary>
<br />
<table>
<tr>
<td>Happy: TARGET_GROUP_ONLY stacks cannot be deleted and recreated</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
[CCIE-1985](https://czi-tech.atlassian.net/browse/CCIE-1985?atlOrigin=eyJpIjoiZDI3Y2ExZWZjYzI0NDQxZTk0ODA4ZjUzNDRiNGMzNzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
AWS has annoying and different name requirements. This fixes the name requirements for target group names. 
* Target groups can be a most 32 chars
* Target groups can't have underscores
[CCIE-1985]: https://czi-tech.atlassian.net/browse/CCIE-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
> fix: trim the target group name to only 32 chars

- api/pkg/ent/appconfig.go
- api/pkg/ent/appconfig/appconfig.go
- api/pkg/ent/appconfig/where.go
- api/pkg/ent/appconfig_create.go
- api/pkg/ent/appconfig_update.go
- api/pkg/ent/client.go
- api/pkg/ent/migrate/schema.go
- api/pkg/ent/mutation.go
- api/pkg/ent/runtime.go
- api/pkg/ent/runtime/runtime.go
- api/pkg/ent/schema/appconfig.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1995" title="CCIE-1995" target="_blank">CCIE-1995</a></summary>
<br />
<table>
<tr>
<td>Add source column to Happy API app_configs table</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1995
Adds a `source` column to the app_configs table along with a hook to populate it, allowing us to stop doing the separate logic where we resolve the source at runtime
> feat: add 'source' column to app_configs table

- terraform/modules/happy-github-ci-role/README.md
- terraform/modules/happy-github-ci-role/ecr.tf
- terraform/modules/happy-github-ci-role/variables.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2010" title="CCIE-2010" target="_blank">CCIE-2010</a></summary>
<br />
<table>
<tr>
<td>Allow module to be used across AWS accounts</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2010?atlOrigin=eyJpIjoiNDg5ODEyMzVlMWRkNGUxMmI0Zjc2NjJiNzNiZmY0YjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
This allows the caller to change the AWS account that the ECR lives in. If nothing is specified, it will use the current account that it i s being executed. This is helpful when we need to grant one CI role access to other happy environments.
> feat: allow AWS account ID to change for ECR policy

- terraform/modules/happy-service-eks/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2061" title="CCIE-2061" target="_blank">CCIE-2061</a></summary>
<br />
<table>
<tr>
<td>Happy: When pod disruption budget is set of 1-pod deployments it blocks rotation of EKS nodes</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
[CCIE-2061]
[CCIE-2061]: https://czi-tech.atlassian.net/browse/CCIE-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Do not create a pod disruption budget for deployment with the desired_count=max_unavailable_count

- terraform/modules/happy-cloudfront/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2070" title="CCIE-2070" target="_blank">CCIE-2070</a></summary>
<br />
<table>
<tr>
<td>CloudFront Happy Stacks Not Redirecting to HTTPS</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2070?atlOrigin=eyJpIjoiY2RkNjJlYTcyZDE2NDZlNmExYThjZTFiNTg3MTRhOTMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
This PR fixes a bug where the default configuration of CloudFront was to only allow HTTPS traffic. While that is the behavior we want, we want to redirect all HTTP traffic to the HTTPS endpoint, not just block HTTP traffic.
> fix: redirect HTTP traffic to HTTPS from viewer to CloudFront

- terraform/modules/happy-cloudfront/README.md
- terraform/modules/happy-cloudfront/main.tf
- terraform/modules/happy-cloudfront/variables.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2075" title="CCIE-2075" target="_blank">CCIE-2075</a></summary>
<br />
<table>
<tr>
<td>Allow POST in cloudfront for Happy</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Is this used by anyone other than ITBS?  I'm changing the default behavior here.
CCIE-2075
> feat: separate configuration of allow methods and allowed cache methods

- shared/backend/aws/k8s_compute_backend.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2083" title="CCIE-2083" target="_blank">CCIE-2083</a></summary>
<br />
<table>
<tr>
<td>Happy: Wait for the pods to appear before failing when migration job runs</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null
> fix: Wait for the pods to appear before failing when migration job runs

- cli/cmd/tags.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2089" title="CCIE-2089" target="_blank">CCIE-2089</a></summary>
<br />
<table>
<tr>
<td>On-Call: Happy: Make addtags command help clearer</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null
> fix: CCIE-2089: Make happy addtags command help clearer

- .github/workflows/charts-release.yml
<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2108]
[CCIE-2108]: https://czi-tech.atlassian.net/browse/CCIE-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix helm chart release regex

- shared/util/github.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2127" title="CCIE-2127" target="_blank">CCIE-2127</a></summary>
<br />
<table>
<tr>
<td>Happy: Impossible to run happy commands when the app folder is not under source control</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2127]
[CCIE-2127]: https://czi-tech.atlassian.net/browse/CCIE-2127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Happy validations fail when an app folder is not version controlled

- api/main.go
- api/pkg/api/app.go
- api/pkg/api/app_ent.go
- api/pkg/api/app_ent_test.go
- api/pkg/api/app_fiber.go
- api/pkg/api/app_test.go
- api/pkg/api/config_group.go
- api/pkg/api/config_group_test.go
- api/pkg/ent/entc.go
- api/pkg/ent/ogent/oas_json_gen.go
- api/pkg/ent/ogent/oas_schemas_gen.go
- api/pkg/ent/openapi.json
- api/pkg/ent/ts/schema.d.ts
- api/pkg/request/health_handler.go
- api/pkg/request/version_check_handler.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2066" title="CCIE-2066" target="_blank">CCIE-2066</a></summary>
<br />
<table>
<tr>
<td>Finallize entoas/ogent read-only routes in Happy API</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
After implementing the new routing in support of /v2 routes, anything that was previously a root route (ie `/health`) in Fiber became inaccessible because only routes prefixed with `/v1` were routed to the Fiber app. This prevented liveness probes from getting a success response and the API was not able to deploy. This moves health and versionCheck routes to the root mux instead of the Fiber app and rewrites tests to be agnostic to the backend …
> fix: implement root health handler

- shared/workspace_repo/workspace.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2153" title="CCIE-2153" target="_blank">CCIE-2153</a></summary>
<br />
<table>
<tr>
<td>Happy terminates if the service configured in config.json doesn't get deployed in a specific environment</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null
> fix: Happy terminates if the service configured in config.json doesn't get deployed in a specific environment

- .github/workflows/integration-test.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2165" title="CCIE-2165" target="_blank">CCIE-2165</a></summary>
<br />
<table>
<tr>
<td>Integration test fails when multiple tests run in parallel</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
We can't use the step to check if certain files changed unless it is a PR that triggered the run
> chore: fix failing integration-test filter when triggered by push

- api/go.mod
- api/go.sum
- api/pkg/api/app.go
- api/pkg/api/app_fiber.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2216" title="CCIE-2216" target="_blank">CCIE-2216</a></summary>
<br />
<table>
<tr>
<td>Configure CORS for v2 routes</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Move the CORS configuration to the root mux so it applies to both v1 and v2 routes, allowing `/v2/app-configs` to be used by EngPortal's Happy plugin
> feat: move cors configuration to root mux

- .github/workflows/api-release-npm.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2224" title="CCIE-2224" target="_blank">CCIE-2224</a></summary>
<br />
<table>
<tr>
<td>Publish hapi TS package</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Fix paths to account for nesting in `api/` directory
> fix: update npm release job to account for monorepo

- api/pkg/api/app.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2216" title="CCIE-2216" target="_blank">CCIE-2216</a></summary>
<br />
<table>
<tr>
<td>Configure CORS for v2 routes</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
Default allowed methods are `http.MethodGet, http.MethodPost, http.MethodHead` but we also need to allow delete requests
> fix: make CORS policy allow delete requests

- api/pkg/api/config_v2.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2217" title="CCIE-2217" target="_blank">CCIE-2217</a></summary>
<br />
<table>
<tr>
<td>Implement v2 API calls in eng-portal</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Leaves the value of `stack` in the API responses blank for env-level configs
> fix: omit stack when config source == 'environment'

- docs/features/config.md
- docs/features/index.md
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2302" title="CCIE-2302" target="_blank">CCIE-2302</a></summary>
<br />
<table>
<tr>
<td>Document how to enable happy config v2</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null
> chore: add doc for migrating from happy config v1 to v2

- cli/cmd/restart.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2299" title="CCIE-2299" target="_blank">CCIE-2299</a></summary>
<br />
<table>
<tr>
<td>Fix command usage for happy restart</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null
> fix: Fix command usage for happy restart

- shared/model/app_stack.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2333" title="CCIE-2333" target="_blank">CCIE-2333</a></summary>
<br />
<table>
<tr>
<td>ONCALL API error</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2333
When calling the API from a Github Action, we don't specify an AWSProfile since there are none. Removing this validation so folks can write Github Actions that call the API.
> fix: aws_profile not always required

- .github/workflows/cleanup-playground.yml
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2114" title="CCIE-2114" target="_blank">CCIE-2114</a></summary>
<br />
<table>
<tr>
<td>Happy cleanup doesn't run</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2114
`Error: request failed with: failed to get oidc token: failed to get token: Unable to extract token from client: could not read from keyring: exec: "dbus-launch": executable file not found in $PATH`
https://github.com/chanzuckerberg/github-actions/pull/248
> fix: update cleanup action to not error out

- shared/workspace_repo/workspace.go
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2592" title="CCIE-2592" target="_blank">CCIE-2592</a></summary>
<br />
<table>
<tr>
<td>Happy: Do not print logs when env var HAPPY_SKIP_LOGS=true is set</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
[CCIE-2592](https://czi-tech.atlassian.net/browse/CCIE-2592)
There is one more place where pod logs are printed. When the TFE plan fails, it was also printing logs.
[CCIE-2592]: https://czi-tech.atlassian.net/browse/CCIE-2592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: printing logs when TFE plan fails

- cli/go.mod
- cli/go.sum
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2717" title="CCIE-2717" target="_blank">CCIE-2717</a></summary>
<br />
<table>
<tr>
<td>Happy list fails to decompress uncompressed token</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2717
When an older (uncompressed) token was cached and someone used a new version of the CLI we'd hit this error:
```
» happy list                                                                                                                                           
[INFO]: Listing stacks from the happy api
[FATAL]: request failed with: failed to get oidc token: failed to get token: Unable to …
```
> fix: use patched oidc_cli version

- api/.happy/terraform/envs/prod/main.tf
- api/.happy/terraform/envs/rdev/main.tf
- api/.happy/terraform/envs/staging/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2722" title="CCIE-2722" target="_blank">CCIE-2722</a></summary>
<br />
<table>
<tr>
<td>https://czi-tech.atlassian.net/browse/ONCALL-776</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2722
This PR increases the idle timeout period for HAPI. Some of the list operations take a little longer and we don't want to return 504 when that happens (like on clean up stack).
* https://chanzuckerbergteam.slack.com/archives/C04NVSCDFR7/p1714430262918409
* https://github.com/chanzuckerberg/bento/actions/runs/8902558405/job/24645287282
> feat: increase the ALB idle timeout period

- terraform/modules/happy-env-ecs/db.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2832" title="CCIE-2832" target="_blank">CCIE-2832</a></summary>
<br />
<table>
<tr>
<td>Update default happy RDS CA identifier</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2832]
[CCIE-2832]: https://czi-tech.atlassian.net/browse/CCIE-2832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Upgrade default RDS certificate bundle for happy-env-ecs to rds-ca-ecc384-g1

- Dockerfile.api
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2924" title="CCIE-2924" target="_blank">CCIE-2924</a></summary>
<br />
<table>
<tr>
<td>Install certificate bundle into hapi container</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
[CCIE-2924]
[CCIE-2924]: https://czi-tech.atlassian.net/browse/CCIE-2924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Restore the HAPI entrypoint

- Dockerfile.api
- terraform/modules/happy-env-ecs/db.tf
- terraform/modules/happy-env-eks/db.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2932" title="CCIE-2932" target="_blank">CCIE-2932</a></summary>
<br />
<table>
<tr>
<td>Modify happy-env-* modules to use rds-ca-rsa2048-g1 CA identifier</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2932]
[CCIE-2932]: https://czi-tech.atlassian.net/browse/CCIE-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR modifies the happy-env-eks and happy-env-ecs modules to use the `rds-ca-rsa2048-g1` CA identifier, as 
`rds-ca-ecc384-g1` requires TLS 1.3, which is not currently compatible with AWS Aurora.
> fix: Update default CA identifier to rds-ca-rsa2048-g1

- terraform/modules/happy-mesh-access-control/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-3091" title="CCIE-3091" target="_blank">CCIE-3091</a></summary>
<br />
<table>
<tr>
<td>Add empty string check to service_account_name</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
CCIE-3091
https://czi-tech.atlassian.net/browse/CCIE-3091
For the `allow_mesh_services` list, we need to supply elements with mixed configuration, stack/service and service_account_name. This is new, previously we mostly only used stack/service
But since mixed structures are not allowed, I had to set empty strings for the values not needed, which caused the incorrect part of ternary to be executed. 
This PR adds an additional non-empty string …
> fix: Add empty string check to service_account_name

- terraform/modules/happy-cloudfront/.validate/main.tf
- terraform/modules/happy-cloudfront/README.md
- terraform/modules/happy-cloudfront/main.tf
- terraform/modules/happy-cloudfront/variables.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-3093" title="CCIE-3093" target="_blank">CCIE-3093</a></summary>
<br />
<table>
<tr>
<td>Make CloudFront Module Accept Multiple Origins</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
People might want to route traffic from one "frontend" endpoint to other endpoints. This change assumes that the path of the frontend domain maps to the same kind of destination endpoint. For example:
example.com/api/oauth -> example2.com/api/oauth
or 
example.com/ -> example2.com/
If you need to deviate from this pattern, you'd have to refactor the `origin`, `cache` blocks, and `variables` to make it work. …
> feat!: allow cloudfront module to use multiple origins

- terraform/modules/happy-mesh-access-control/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-3100" title="CCIE-3100" target="_blank">CCIE-3100</a></summary>
<br />
<table>
<tr>
<td>Happy allow for status page internal</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-3100
> feat: allow status page for all happy services

- terraform/modules/happy-mesh-access-control/main.tf
<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-3110" title="CCIE-3110" target="_blank">CCIE-3110</a></summary>
<br />
<table>
<tr>
<td>Fix Issue with IdentityRef format in linkerd</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-3110
Reverts chanzuckerberg/happy#3414
Issue - https://si.prod.tfe.czi.technology/app/happy-edu-platform/workspaces/staging-cts/runs/run-oS9Kpgupg5gGgKTe
> fix: revert "feat: allow status page for all happy services"

- api/pkg/request/auth.go
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3389" title="CCIE-3389" target="_blank">CCIE-3389</a></summary>
<br />
<table>
<tr>
<td>Fix Happy API to not panic when we clean up old OIDC providers</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-3389
> fix: don't panic when an OIDC provider doesn't exist anymore

- terraform/modules/happy-datadog-synthetics/README.md
- terraform/modules/happy-datadog-synthetics/main.tf
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3479" title="CCIE-3479" target="_blank">CCIE-3479</a></summary>
<br />
<table>
<tr>
<td>Reduce number of synthetic check locations used for happy stacks to us-east-1 and us-west-2</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
[ONCALL-937] [CCIE-3479]
[ONCALL-937]: https://czi.atlassian.net/browse/ONCALL-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCIE-3479]: https://czi.atlassian.net/browse/CCIE-3479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Restrict happy datadog synthetics to us-east-1 and us-west-2

- terraform/modules/happy-stack-eks/synthetics.tf
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3522" title="CCIE-3522" target="_blank">CCIE-3522</a></summary>
<br />
<table>
<tr>
<td>Too many synthetics being made for custom happy domains</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-3522
Noticed there were some faulty synthetics for custom production domains. After reviewing the code, these [projects](https://github.com/chanzuckerberg/bento/blob/main/apps/login/.happy/terraform/envs/prod/main.tf) didn't actually have synthetics turned on, but its because this file will make synthetics for all custom domains, regardless of if you set it. Adding a filter to only add synthetics if …
> fix: only create synthetics if they request it

- .github/workflows/cli-release.yaml
- cli/cmd/api.go
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3758" title="CCIE-3758" target="_blank">CCIE-3758</a></summary>
<br />
<table>
<tr>
<td>Upgrade TFE Prod</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-3758
https://github.com/hashicorp/ghaction-terraform-provider-release/issues/36
> fix: deprecated --rm-dist flag for goreleaser

- shared/stack/stack.go
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3967" title="CCIE-3967" target="_blank">CCIE-3967</a></summary>
<br />
<table>
<tr>
<td>Fix unsafe quotation in Happy</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Addresses a critical alert https://github.com/chanzuckerberg/happy/security/code-scanning/2
[CCIE-3967]
[CCIE-3967]: https://czi.atlassian.net/browse/CCIE-3967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix unsafe quotation

- terraform/modules/happy-service-eks/main.tf
- terraform/modules/happy-stack-eks/README.md
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3991" title="CCIE-3991" target="_blank">CCIE-3991</a></summary>
<br />
<table>
<tr>
<td>bug: Happy ignores sticky session settings</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-3991
> fix: Fix the default sticky session behavior in happy-nginx-ingress-eks

- terraform/modules/happy-service-eks/main.tf
- terraform/modules/happy-stack-eks/README.md
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3991" title="CCIE-3991" target="_blank">CCIE-3991</a></summary>
<br />
<table>
<tr>
<td>bug: Happy ignores sticky session settings</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
[CCIE-3991]
[CCIE-3991]: https://czi.atlassian.net/browse/CCIE-3991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix sticky sessions

- .github/workflows/api-release-npm.yml
- .github/workflows/api-release-prod.yaml
- .github/workflows/api-release-staging.yaml
- .github/workflows/api-update-docs.yml
- .github/workflows/api-update-ent-schema.yml
- .github/workflows/automerge-dep.yml
- .github/workflows/charts-release.yml
- .github/workflows/cleanup-playground.yml
- .github/workflows/cli-ci.yml
- .github/workflows/cli-release.yaml
- .github/workflows/conventional-commits.yml
- .github/workflows/hvm-ci.yml
- .github/workflows/hvm-release.yaml
- .github/workflows/jira-pr.yaml
- .github/workflows/provider-ci.yml
- .github/workflows/provider-release.yaml
- .github/workflows/provider-update-docs.yml
- .github/workflows/release-please.yaml
- .github/workflows/shared-ci.yml
- .github/workflows/tf-ci.yml
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3911" title="CCIE-3911" target="_blank">CCIE-3911</a></summary>
<br />
<table>
<tr>
<td>Deprecate "self-hosted" and "Linux" tags</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
> fix: Update runs-on labels in GitHub Actions workflows

- terraform/provider/.golangci.yml
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-4307" title="CCIE-4307" target="_blank">CCIE-4307</a></summary>
<br />
<table>
<tr>
<td>Fix Happy Linter</td>
</tr>
<tr>
<th>Type</th>
<td>
Sub-task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Lint had a breaking change a while back involving depguard drastically rewriting the structure of its config (https://github.com/golangci/golangci-lint/issues/3906) . I took a stab at rewriting to meet the new standard (https://golangci-lint.run/usage/linters/#depguard) but in realizing what this specific linter did, it didn't seem worth debugging the associated versioning and formatting issues. As this specific linter was primarily being used to ensure we were not using …
> fix: remove depguard from happy linter (CCIE-4307)

- terraform/modules/happy-env-eks/README.md
- terraform/modules/happy-env-eks/oidc.tf
<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-4359" title="CCIE-4359" target="_blank">CCIE-4359</a></summary>
<br />
<table>
<tr>
<td>Upgrade okta provider</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Need `happy-env-eks` to pick up most recent version of `happy-tfe-okta-app` with new provider version requirements.
> fix: Pin happy-tfe-okta-app in happy-env-eks
