.goreleaser.yml

https://app.shortcut.com/infraeng/story/180461/change-cli-name-from-happy-deploy-to-happy

chore!: We call the binary "happy" rather than happy deploy

---

pkg/artifact_builder/builder_config.go

fix: add HAPPY_ENV={env} to docker build args

---

release-please-config.json

tell release please to use the next minor version in https://github.com/chanzuckerberg/happy/pull/616 instead of releasing v1.0.0

fix: specify release

---

release-please-config.json

release the version pin so we don't re-release the same version

chore: remove release-as

---

api/app-config.yaml
api/go.mod
api/go.sum
api/pkg/api/app.go
api/pkg/request/auth.go
api/pkg/request/auth_test.go
api/pkg/setup/setup.go

This PR changes the configuration to allow for multiple OIDC providers.

feat: allow for configuration to present n oidc

---

README.md
terraform/modules/happy-env-eks/README.md

Empty PR to trigger a new release please PR.

feat: release please bump

---

terraform/modules/happy-env-ecs/README.md

This PR just triggers a feature release of this module since I used a chore in #951

feat: metrics server

---

api/.happy/catalog-info.yaml

This PR was created with EngPortal using the "Register Existing Happy App in Software Catalog" software template. It creates a component YAML file and registers the component in the Eng-Portal Software Catalog.

chore: add to software catalog

---

.github/workflows/api-ci.yml
.github/workflows/cli-ci.yml
.github/workflows/provider-ci.yml
.github/workflows/shared-ci.yml

https://github.com/golangci/golangci-lint-action/issues/677

fix: golanglint-ci

---

terraform/modules/happy-env-eks/README.md

pins prod for the service account

fix: bump happy-env-eks version

---

cli/pkg/output/printer_factory.go

fix: happy list no longer displays service endpoints

---

docs/Deploy_An_Application.md
docs/Installing_Happy_Path.md
docs/README.md
docs/Service_Discovery_In_EKS.md
docs/Using_External_DNS_Tooling.md

This aims to add a first pass at Happy Path user documentation.

feat: Add Happy User Documentation

---

terraform/modules/happy-stack-eks/variables.tf

Fixes nested validation rules for sidecars.

fix: Fix sidecar validation rules

---

shared/workspace_repo/workspace.go

This change allows us to support both structured and console output logging.

fix: Happy logs look weird when workspace has new format

---

cli/cmd/delete.go
cli/cmd/init.go
cli/cmd/root.go

This PR fixes a deadlock in deletes because the worker pool isn't started.

fix: deadlock in deletes

---

.github/workflows/integration-test.yml
.github/workflows/tf-ci.yml

It failed due to the `happy list --output json` format change.

fix: Fix the integration test

---

terraform/modules/happy-env-eks/README.md

Just triggering a new version of happy-env-eks

feat: support EKS paths for new service accounts

---

cli/cmd/migrate.go
cli/cmd/resources.go
cli/pkg/orchestrator/orchestrator_test.go

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1603" title="CCIE-1603" target="_blank">CCIE-1603</a></summary>
<br />
<table>
<tr>
<td>'happy list --output json'  returns an invalid value</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
Fixes [CCIE-1603]
[CCIE-1603]: https://czi-tech.atlassian.net/browse/CCIE-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Tasks when executed do not receive environment information

---

.github/workflows/api-ci.yml
.github/workflows/api-update-docs.yml
.github/workflows/cli-ci.yml
.github/workflows/provider-ci.yml
.github/workflows/provider-update-docs.yml
.github/workflows/shared-ci.yml
.github/workflows/tf-ci.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1599" title="CCIE-1599" target="_blank">CCIE-1599</a></summary>
<br />
<table>
<tr>
<td>Improve conditional happy CI logic to prevent bot from merging broken code</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null

feat: update conditional job execution to allow jobs to be required by branch protection

---

.github/workflows/automerge-dep.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1599" title="CCIE-1599" target="_blank">CCIE-1599</a></summary>
<br />
<table>
<tr>
<td>Improve conditional happy CI logic to prevent bot from merging broken code</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1599

fix: change merge to squash

---

terraform/modules/happy-service-eks/main.tf

Env vars to help our libraries (ex: observability) know more contextual info.

feat: Adding HAPPY_STACK and HAPPY_SERVICE env vars

---

.github/workflows/jira-release.yaml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1651" title="CCIE-1651" target="_blank">CCIE-1651</a></summary>
<br />
<table>
<tr>
<td>Independent release announcements for happy cli and api</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1651

chore: simplify jira release title

---

terraform/modules/happy-service-eks/tags.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1686" title="CCIE-1686" target="_blank">CCIE-1686</a></summary>
<br />
<table>
<tr>
<td>Add service type and service name to happy routing tags</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
CCIE-1686

fix: adding service type and service name to happy routing tags

---

terraform/modules/happy-env-eks/variables.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1702" title="CCIE-1702" target="_blank">CCIE-1702</a></summary>
<br />
<table>
<tr>
<td>Allow for Bucket Policies to be Configured for Happy S3 Buckets</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1702](https://czi-tech.atlassian.net/browse/CCIE-1702)
[CCIE-1702]: https://czi-tech.atlassian.net/browse/CCIE-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add policy variable for s3 buckets

---

terraform/modules/happy-env-ecs/README.md
terraform/modules/happy-env-ecs/ci_role.tf
terraform/modules/happy-env-ecs/dynamo.tf
terraform/modules/happy-env-ecs/ecr.tf
terraform/modules/happy-env-ecs/integration_secret.tf
terraform/modules/happy-env-ecs/main.tf
terraform/modules/happy-env-ecs/variables.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1704" title="CCIE-1704" target="_blank">CCIE-1704</a></summary>
<br />
<table>
<tr>
<td>Upgrade happy-env-ecs and esc-test-app-infra happy to fix the happy provider issues</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
A part of [CCIE-1704].
[CCIE-1704]: https://czi-tech.atlassian.net/browse/CCIE-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix!: Arguments missing from happy_github_ci_role

---

terraform/modules/happy-stack-ecs/versions.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1704" title="CCIE-1704" target="_blank">CCIE-1704</a></summary>
<br />
<table>
<tr>
<td>Upgrade happy-env-ecs and esc-test-app-infra happy to fix the happy provider issues</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1704]
[CCIE-1704]: https://czi-tech.atlassian.net/browse/CCIE-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Upgrade happy provider version in happy-env-ecs

---

.github/dependabot.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1714" title="CCIE-1714" target="_blank">CCIE-1714</a></summary>
<br />
<table>
<tr>
<td>Skip coverage updates on dependabot PRs</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1714]
[CCIE-1714]: https://czi-tech.atlassian.net/browse/CCIE-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Move dependabot schedule to a weekly cycle

---

api/.happy/api-info.yaml
api/.happy/catalog-info.yaml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1715" title="CCIE-1715" target="_blank">CCIE-1715</a></summary>
<br />
<table>
<tr>
<td>Populate catalog with core infra products</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null

chore: [catalog-info] add hapi to core-platform system

---

terraform/modules/happy-ingress-eks/README.md
terraform/modules/happy-ingress-eks/main.tf
terraform/modules/happy-ingress-eks/variables.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1758" title="CCIE-1758" target="_blank">CCIE-1758</a></summary>
<br />
<table>
<tr>
<td>Make the health check of the target group configurable</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
CCIE-1758 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/#health-check

feat: increase the health check interval

---

api/pkg/api/app.go
api/pkg/request/auth.go

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1752" title="CCIE-1752" target="_blank">CCIE-1752</a></summary>
<br />
<table>
<tr>
<td>Configure Sentry for happy api</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
[CCIE-1752](https://czi-tech.atlassian.net/browse/CCIE-1752)
[CCIE-1752]: https://czi-tech.atlassian.net/browse/CCIE-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add github actor to sentry info

---

.release-please-manifest.json
api/CHANGELOG.md
cli/CHANGELOG.md
hvm/CHANGELOG.md
shared/CHANGELOG.md
terraform/provider/CHANGELOG.md

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1619" title="CCIE-1619" target="_blank">CCIE-1619</a></summary>
<br />
<table>
<tr>
<td>Finish up v1 of Happy Version Manager</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
Reverts chanzuckerberg/happy#2390
[CCIE-1619](https://czi-tech.atlassian.net/browse/CCIE-1619)
[CCIE-1619]: https://czi-tech.atlassian.net/browse/CCIE-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Revert "chore: release main"

---

release-please-config.json

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1777" title="CCIE-1777" target="_blank">CCIE-1777</a></summary>
<br />
<table>
<tr>
<td>Fix release-please versions in happy</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1777

chore: fix release please

---

hvm/.goreleaser.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1779" title="CCIE-1779" target="_blank">CCIE-1779</a></summary>
<br />
<table>
<tr>
<td>Happy api 403s</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null

fix: hvm asset naming

---

terraform/modules/happy-env-ecs/README.md
terraform/modules/happy-env-ecs/ecr.tf
terraform/modules/happy-env-ecs/proxy.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1825" title="CCIE-1825" target="_blank">CCIE-1825</a></summary>
<br />
<table>
<tr>
<td>Upgrade OAuth2 Proxy for Single Cell</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1825
This PR picks up the changes from underlying modules.

fix: wrong outputs and ecr types

---

terraform/modules/happy-env-eks/oidc.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1844" title="CCIE-1844" target="_blank">CCIE-1844</a></summary>
<br />
<table>
<tr>
<td>Configure Okta OIDC App for Scruffy </td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
[CCIE-1844](https://czi-tech.atlassian.net/browse/CCIE-1844)
[CCIE-1844]: https://czi-tech.atlassian.net/browse/CCIE-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: thread through the token auth config

---

shared/config/bootstrap_test.go
shared/config/happy_config.go

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1893" title="CCIE-1893" target="_blank">CCIE-1893</a></summary>
<br />
<table>
<tr>
<td>Docker compose env file discovery doesn't work</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1893]
[CCIE-1893]: https://czi-tech.atlassian.net/browse/CCIE-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Docker compose env file discovery doesn't work

---

cli/pkg/artifact_builder/artifact_builder.go
terraform/modules/happy-github-ci-role/README.md
terraform/modules/happy-github-ci-role/ecr.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1902" title="CCIE-1902" target="_blank">CCIE-1902</a></summary>
<br />
<table>
<tr>
<td>When ECR scanning is not enable, happy update fails</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1902]
[CCIE-1902]: https://czi-tech.atlassian.net/browse/CCIE-1902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix ECR scanning when scanning is not enabled

---

terraform/modules/happy-env-eks/README.md

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1902" title="CCIE-1902" target="_blank">CCIE-1902</a></summary>
<br />
<table>
<tr>
<td>When ECR scanning is not enable, happy update fails</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1902]
[CCIE-1902]: https://czi-tech.atlassian.net/browse/CCIE-1902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Bump happy-env-eks

---

examples/integration_test/.happy/config.json
examples/integration_test/.happy/terraform/envs/rdev/main.tf
shared/util/maps.go

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1905" title="CCIE-1905" target="_blank">CCIE-1905</a></summary>
<br />
<table>
<tr>
<td>Happy infra ingest fails when scan_on_push="true" (mismatched type)</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-1905]
[CCIE-1905]: https://czi-tech.atlassian.net/browse/CCIE-1905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix integration test (mismatched parameter type)

---

release-please-config.json

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1853" title="CCIE-1853" target="_blank">CCIE-1853</a></summary>
<br />
<table>
<tr>
<td>Cloudfront added to stack module</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
[CCIE-1853](https://czi-tech.atlassian.net/browse/CCIE-1853)
[CCIE-1853]: https://czi-tech.atlassian.net/browse/CCIE-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add happy-cloudfront to release-please

---

Dockerfile.api
api/pkg/dbutil/db.go
api/tools/db-shell.sh

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1925" title="CCIE-1925" target="_blank">CCIE-1925</a></summary>
<br />
<table>
<tr>
<td>Remove unused stacks logic from happy api</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
null

feat: remove unused stacks table

---

terraform/modules/happy-github-ci-role/ecr.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2010" title="CCIE-2010" target="_blank">CCIE-2010</a></summary>
<br />
<table>
<tr>
<td>Allow module to be used across AWS accounts</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-2010

fix: typo for locals

---

terraform/modules/happy-stack-ecs/README.md
terraform/modules/happy-stack-ecs/versions.tf
terraform/modules/happy-stack-eks/README.md
terraform/modules/happy-stack-eks/versions.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1780" title="CCIE-1780" target="_blank">CCIE-1780</a></summary>
<br />
<table>
<tr>
<td>Create custom claim for happy api tokens from happy tf provider</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
https://czi-tech.atlassian.net/browse/CCIE-1914

feat: bump happy provider version

---

cli/go.mod
cli/go.sum
shared/client/util.go

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-1748" title="CCIE-1748" target="_blank">CCIE-1748</a></summary>
<br />
<table>
<tr>
<td>Batch Multiple Deletes Using Happy Delete</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Follow-up to [CCIE-1748](https://czi-tech.atlassian.net/browse/CCIE-1748) to fix a failing check
[CCIE-1748]: https://czi-tech.atlassian.net/browse/CCIE-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: sync go versions

---

helm-charts/charts/stack/templates/_helpers.tpl
helm-charts/charts/stack/templates/cronjob.yaml
helm-charts/charts/stack/templates/deployment.yaml
helm-charts/charts/stack/templates/ingress_bypass.yaml
helm-charts/charts/stack/templates/ingress_main.yaml
helm-charts/charts/stack/templates/linkerd_authz_policy.yaml
helm-charts/charts/stack/templates/linkerd_ingress.yaml
helm-charts/charts/stack/templates/linkerd_mesh_tls_auth.yaml
helm-charts/charts/stack/templates/linkerd_server.yaml
helm-charts/charts/stack/templates/pdb.yaml
helm-charts/charts/stack/templates/sa.yaml
helm-charts/charts/stack/values.yaml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2028" title="CCIE-2028" target="_blank">CCIE-2028</a></summary>
<br />
<table>
<tr>
<td>Happy: Add pod disruption budgets support for the helm chart</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null

feat: Chart cleanup and pod disruption budgets support

---

.release-please-manifest.json

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
CCIE-2108

feat: Version happy-stack-helm-eks module

---

release-please-config.json

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
CCIE-2108

fix: Removed pinned version from the helm-chart in release-please-config

---

.github/workflows/charts-release.yml
helm-charts/charts/stack/templates/_helpers.tpl

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
CCIE-2108

fix: Fix chart index yaml copy

---

.github/workflows/charts-release.yml
helm-charts/charts/stack/templates/_helpers.tpl

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2108]
[CCIE-2108]: https://czi-tech.atlassian.net/browse/CCIE-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix semantic version errors in chart release process

---

helm-charts/charts/stack/templates/_helpers.tpl

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2108]
[CCIE-2108]: https://czi-tech.atlassian.net/browse/CCIE-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update the helm chart

---

.github/workflows/charts-release.yml
helm-charts/charts/stack/templates/_helpers.tpl

<details open>
<br />
<table>
<tr>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2108]
[CCIE-2108]: https://czi-tech.atlassian.net/browse/CCIE-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Variable resolution in helm chart releases

---

.github/workflows/cleanup-playground.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2114" title="CCIE-2114" target="_blank">CCIE-2114</a></summary>
<br />
<table>
<tr>
<td>Happy cleanup doesn't run</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2114]
[CCIE-2114]: https://czi-tech.atlassian.net/browse/CCIE-2114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix happy cleanup

---

README.md

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2145" title="CCIE-2145" target="_blank">CCIE-2145</a></summary>
<br />
<table>
<tr>
<td>Happy: Improve readme by describing the integration secret creation process</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2145]
[CCIE-2145]: https://czi-tech.atlassian.net/browse/CCIE-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Improve happy onboarding documentation (integration secret creation)

---

README.md

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2145" title="CCIE-2145" target="_blank">CCIE-2145</a></summary>
<br />
<table>
<tr>
<td>Happy: Improve readme by describing the integration secret creation process</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2145]
[CCIE-2145]: https://czi-tech.atlassian.net/browse/CCIE-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix a typo in a readme

---

.github/workflows/integration-test.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2165" title="CCIE-2165" target="_blank">CCIE-2165</a></summary>
<br />
<table>
<tr>
<td>Integration test fails when multiple tests run in parallel</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2165]
[CCIE-2165]: https://czi-tech.atlassian.net/browse/CCIE-2165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix "already exists" error in the integration test

---

api/go.mod
cli/go.mod
shared/go.mod

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2215" title="CCIE-2215" target="_blank">CCIE-2215</a></summary>
<br />
<table>
<tr>
<td>Pin k8s packages in happy</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2215]
[CCIE-2215]: https://czi-tech.atlassian.net/browse/CCIE-2215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Pin k8s client to v0.28.4

---

shared/hclmanager/hcl_manager.go
shared/util/tf/tf_parser.go

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2317" title="CCIE-2317" target="_blank">CCIE-2317</a></summary>
<br />
<table>
<tr>
<td>Slow happy cli</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
null

feat: Troubleshooting slow happy cli

---

terraform/modules/happy-service-eks/main.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2196" title="CCIE-2196" target="_blank">CCIE-2196</a></summary>
<br />
<table>
<tr>
<td>Update TF modules to include Happy Config secrets</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---

feat: inject v2 configs into sidecars

---

.github/workflows/integration-test.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2377" title="CCIE-2377" target="_blank">CCIE-2377</a></summary>
<br />
<table>
<tr>
<td>Happy: Trigger integration test when a label "test" is added to a PR</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
null

feat: Trigger integration test when a label "happy:integration-test" is added to a PR

---

.github/workflows/integration-test.yml

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2377" title="CCIE-2377" target="_blank">CCIE-2377</a></summary>
<br />
<table>
<tr>
<td>Happy: Trigger integration test when a label "test" is added to a PR</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
null

feat: Trigger integration test when a label "test" is added to a PR

---

README.md

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2377" title="CCIE-2377" target="_blank">CCIE-2377</a></summary>
<br />
<table>
<tr>
<td>Happy: Trigger integration test when a label "test" is added to a PR</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
null

chore: Readme note on labeling of the PRs to trigger integration testing

---

terraform/modules/happy-env-eks/versions.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2697" title="CCIE-2697" target="_blank">CCIE-2697</a></summary>
<br />
<table>
<tr>
<td>Implement ECR pull through cache in core-platform prod account</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2697](https://czi-tech.atlassian.net/browse/CCIE-2697)
Release please bump
[CCIE-2697]: https://czi-tech.atlassian.net/browse/CCIE-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: bump happy-env-eks module with new features

---

terraform/modules/happy-env-eks/db.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-2832" title="CCIE-2832" target="_blank">CCIE-2832</a></summary>
<br />
<table>
<tr>
<td>Update default happy RDS CA identifier</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-2832]
[CCIE-2832]: https://czi-tech.atlassian.net/browse/CCIE-2832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Upgrade RDS ca_cert_identifier to rds-ca-ecc384-g1

---

terraform/modules/happy-env-ecs/README.md
terraform/modules/happy-env-ecs/proxy.tf

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-3077" title="CCIE-3077" target="_blank">CCIE-3077</a></summary>
<br />
<table>
<tr>
<td>CLONE - Add PATCH HTTP Method to happy-env-ecs module</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Bump the version of ECS proxy to include the PATCH request.
* https://czi-tech.atlassian.net/browse/ONCALL-824
* https://czi-tech.atlassian.net/browse/CCIE-3077

feat: upgrade proxy to include PATCH in CORS headers

---

terraform/modules/happy-stack-eks/README.md

<details open>
<summary><a href="https://czi-tech.atlassian.net/browse/CCIE-3100" title="CCIE-3100" target="_blank">CCIE-3100</a></summary>
<br />
<table>
<tr>
<td>Happy allow for status page internal</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-3100](https://czi-tech.atlassian.net/browse/CCIE-3100)
[CCIE-3100]: https://czi-tech.atlassian.net/browse/CCIE-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: bump stack module to get new service

---

terraform/modules/happy-stack-eks/README.md

<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3479" title="CCIE-3479" target="_blank">CCIE-3479</a></summary>
<br />
<table>
<tr>
<td>Reduce number of synthetic check locations used for happy stacks to us-east-1 and us-west-2</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
</table>
</details>
---
[CCIE-3479]
[CCIE-3479]: https://czi.atlassian.net/browse/CCIE-3479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Trigger happy-stack-eks release

---

cli/cmd/api.go

https://czi.atlassian.net/browse/CCIE-3758

fix: bump version of the CLI

---

.github/workflows/cli-release.yaml
cli/cmd/api.go
shared/workspace_repo/api_client.go

https://czi.atlassian.net/browse/CCIE-3758

fix: pin version of goreleaser

---

.github/workflows/api-ci.yml

<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3911" title="CCIE-3911" target="_blank">CCIE-3911</a></summary>
<br />
<table>
<tr>
<td>Deprecate "self-hosted" and "Linux" tags</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-3911

chore: update deprecate tags

---

terraform/modules/happy-env-ecs/README.md
terraform/modules/happy-env-ecs/batch.tf
terraform/modules/happy-env-ecs/cluster.tf

<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-3877" title="CCIE-3877" target="_blank">CCIE-3877</a></summary>
<br />
<table>
<tr>
<td>Replace AMI images built by chanzuckerberg/images with suitable alternatives</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
[CCIE-3877](https://czi.atlassian.net/browse/CCIE-3877)
[CCIE-3877]: https://czi.atlassian.net/browse/CCIE-3877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Upgrade happy-env-ecs to use new machine-images

---

terraform/modules/happy-tfe-okta-app/README.md
terraform/modules/happy-tfe-okta-app/main.tf
terraform/modules/happy-tfe-okta-app/versions.tf
terraform/modules/happy-tfe-okta-service-account/.validate/README.md
terraform/modules/happy-tfe-okta-service-account/.validate/versions.tf
terraform/modules/happy-tfe-okta-service-account/README.md
terraform/modules/happy-tfe-okta-service-account/versions.tf

<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-4359" title="CCIE-4359" target="_blank">CCIE-4359</a></summary>
<br />
<table>
<tr>
<td>Upgrade okta provider</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
Upgrading okta provider

feat: Upgrade okta provider to 4.0

---

.github/workflows/api-ci.yml
.github/workflows/charts-release.yml
.github/workflows/tf-ci.yml

<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-4052" title="CCIE-4052" target="_blank">CCIE-4052</a></summary>
<br />
<table>
<tr>
<td>Transition ARM64 and X64 labels to unpriviledged scalesets</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
<td>Done</td>
</tr>
</table>
</details>
---
https://czi.atlassian.net/browse/CCIE-4052

chore: update runs-on

---

.github/workflows/api-update-docs.yml
.github/workflows/api-update-ent-schema.yml
.github/workflows/automerge-dep.yml
.github/workflows/charts-release.yml
.github/workflows/cli-ci.yml
.github/workflows/cli-release.yaml
.github/workflows/hvm-ci.yml
.github/workflows/hvm-release.yaml
.github/workflows/provider-release.yaml
.github/workflows/provider-update-docs.yml
.github/workflows/release-please.yaml
.github/workflows/shared-ci.yml
.github/workflows/tf-ci.yml

<details open>
<summary><a href="https://czi.atlassian.net/browse/CCIE-4332" title="CCIE-4332" target="_blank">CCIE-4332</a></summary>
<br />
<table>
<tr>
<td>Rename all uses of CZI_GITHUB_HELPER_* to GH_ACTIONS_HELPER_</td>
</tr>
<tr>
<th>Type</th>
<td>
Task
</td>
</tr>
<tr>
</tr>
</table>
</details>
---
This is an AI generated PR.
Agent: claude_code
Execution time: 51072 ms
Cost: $0.22

chore: CCIE-4332 use GH_ACTIONS_HELPER_*
